YahooGroups/YahooGroups/Controllers/GroupController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using YahooGroups.Models;
namespace YahooGroups.Controllers
{
    public class GroupController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public ActionResult Index(int? id)
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"].ToString();
            }
            
            var groups = from gr in db.Groups select gr;
            
            ViewBag.Groups = groups.ToList();

            bool IsLogedIn = false;

            if (User.IsInRole("user") || User.IsInRole("moderator") || User.IsInRole("admin"))
            {
                IsLogedIn = true;
            }

            ViewBag.IsLogedIn = IsLogedIn;

            if (User.IsInRole("admin"))
            {
                ViewBag.UserRole = "admin";
            }

            var user = db.Users.Find(User.Identity.GetUserId());
            if (user == null)
            {
                ViewBag.CurrentUserGroups = new List<GroupModels>();
            }
            else
            {
                ViewBag.CurrentUserGroups = user.Groups;
            }

            return View();
        }

        [HttpGet]
        public ActionResult Show(int id)
        {
            GroupModels group = db.Groups.Find(id);
            var moderator = db.Users.Find(group.moderatorId);
            var currentId = User.Identity.GetUserId();
            var user = db.Users.Find(currentId);
            bool hasJoined = false;

            if (!User.IsInRole("admin") && !User.IsInRole("moderator") && !User.IsInRole("user"))
            {
                ViewBag.IsLogedIn = false;
            }
            else
            {
                ViewBag.IsLogedIn = true;
            }

            if (group.Users.Contains(user))
            {
                hasJoined = true;
            }

            ViewBag.Moderator = moderator.UserName;
            ViewBag.Users = group.Users;
            ViewBag.CurrentId = currentId;
            ViewBag.HasJoined = hasJoined;

            if (User.IsInRole("admin"))
            {
                ViewBag.UserRole = "admin";
            }

            if (user == null)
            {
                ViewBag.CurrentUserGroups = new List<GroupModels>();
            }
            else
            {
                ViewBag.CurrentUserGroups = user.Groups;
            }

            return View(group);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            GroupModels gr = db.Groups.Find(id);
            if(gr.moderatorId == User.Identity.GetUserId() || User.IsInRole("admin") || User.IsInRole("moderator"))
            {
                TempData["message"] = "Grupul a fost sters";
                foreach(var user in gr.Users)
                {
                    if (TryUpdateModel(gr))
                    {
                        user.Groups.Remove(gr);
                        db.SaveChanges();
                    }
                }
                foreach (var user in gr.InQueue)
                {
                    if (TryUpdateModel(gr))
                    {
                        user.Groups.Remove(gr);
                        db.SaveChanges();
                    }
                }
                db.Groups.Remove(gr);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Nu ai dreptul sa stergi acest grup";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Kick (int groupId, string userId)
        {
            var user = db.Users.Find(userId);
            var group = db.Groups.Find(groupId);
            var id = groupId;

            if (TryUpdateModel(group))
            {
                group.Users.Remove(user);
                db.SaveChanges();
            }

            return RedirectToAction("Show", new { id });
        }

        [Authorize(Roles = "user,moderator,admin")]
        public ActionResult CreateGroup()
        {
            var group = new GroupModels();

            group.moderatorId = User.Identity.GetUserId();

            ViewBag.Categories = GetAllCategories();

            if (User.IsInRole("admin"))
            {
                ViewBag.UserRole = "admin";
            }

            if (!User.IsInRole("admin") && !User.IsInRole("moderator") && !User.IsInRole("user"))
            {
                ViewBag.IsLogedIn = false;
            }
            else
            {
                ViewBag.IsLogedIn = true;
            }

            var user = db.Users.Find(User.Identity.GetUserId());
            ViewBag.CurrentUserGroups = user.Groups;

            return View(group);
        }
        
        [Authorize(Roles = "user,moderator,admin")]
        [HttpPost]
        public ActionResult CreateGroup(GroupModels group)
        {
            var user = db.Users.Find(group.moderatorId);
            group.Users.Add(user);

            var category = db.Categories.Find(group.CategoryId);

            try
            {
                db.Groups.Add(group);
                db.SaveChanges();
                TempData["message"] = "Grupul a fost adaugat!";

                // Register the user as member of this group
                if (TryUpdateModel(user))
                {
                    user.Groups.Add(group);
                    db.SaveChanges();
                }

                // Register the group as part of category
                if(TryUpdateModel(category))
                {
                    category.Groups.Add(group);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch(Exception e)
            {

                TempData["message"] = e.ToString();
                return View(group);
            }
        }

        [Authorize(Roles = "user,moderator,admin")]
        [HttpPost]
        public ActionResult Join(int groupId, string userId)
        {
            var group = db.Groups.Find(groupId);
            var user = db.Users.Find(userId);
            var id = groupId;

            if (group.privateGroup)
            {
                if (group.InQueue.Contains(user))
                {
                    return RedirectToAction("Show", new { id });
                }
                else
                {
                    if (TryUpdateModel(group))
                    {
                        group.InQueue.Add(user);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Show", new { id });
                }
            }

            if (TryUpdateModel(group))
            {
                group.Users.Add(user);
                db.SaveChanges();
            }

            if (TryUpdateModel(user))
            {
                user.Groups.Add(group);
                db.SaveChanges();   
            }

            return RedirectToAction("Show", new { id });
        }

        [HttpGet]
        public ActionResult Approve (int groupId, string userId)
        {
            var user = db.Users.Find(userId);
            var group = db.Groups.Find(groupId);
            var id = groupId;

            if (TryUpdateModel(group))
            {
                group.InQueue.Remove(user);
                group.Users.Add(user);
                db.SaveChanges();
            }

            if (TryUpdateModel(user))
            {
                user.Groups.Add(group);
                db.SaveChanges();
            }

            return RedirectToAction("Show", new { id });
        }

        [HttpGet]
        public ActionResult Deny(int groupId, string userId)
        {
            var user = db.Users.Find(userId);
            var group = db.Groups.Find(groupId);
            var id = groupId;

            if (TryUpdateModel(group))
            {
                group.InQueue.Remove(user);
                db.SaveChanges();
            }

            return RedirectToAction("Show", new { id });
        }

        [HttpPost]
        public ActionResult Search (string search)
        {
            var Groups = (from gr in db.Groups where gr.groupName.ToUpper().Contains(search.ToUpper()) select gr).ToList();

            ViewBag.Groups = Groups;

            if (User.IsInRole("user") || User.IsInRole("moderator") || User.IsInRole("admin"))
            {
                ViewBag.IsLogedIn = true;
            }
            else
            {
                ViewBag.IsLogedIn = false;
            }

            if (User.IsInRole("admin"))
            {
                ViewBag.UserRole = "admin";
            }

            return View("Index");
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllCategories()
        {
            // generam o lista goala
            var selectList = new List<SelectListItem>();

            
            var categories = from category in db.Categories
                             select category;
            foreach (var category in categories)
            {
                // Adaugam in lista elementele necesare pentru dropdown
                selectList.Add(new SelectListItem
                {
                    Value = category.CategoryId.ToString(),
                    Text = category.Name.ToString()
                });
            }
            return selectList;
        }
    }
}

YahooGroups/YahooGroups/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YahooGroups.Models;

namespace YahooGroups.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            string role = "unreg";

            if (User.IsInRole("admin"))
            {
                role = "admin";
            }
            else if (User.IsInRole("moderator"))
            {
                role = "moderator";
            }
            else if (User.IsInRole("user"))
            {
                role = "user";
            }

            ViewBag.UserRole = role;

            var user = db.Users.Find(User.Identity.GetUserId());

            if (user == null)
            {
                ViewBag.CurrentUserGroups = new List<GroupModels>();
            }
            else
            {
                ViewBag.CurrentUserGroups = user.Groups;
            }

            if (!User.IsInRole("admin") && !User.IsInRole("moderator") && !User.IsInRole("user"))
            {
                ViewBag.IsLogedIn = false;
            }
            else
            {
                ViewBag.IsLogedIn = true;
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

YahooGroups/YahooGroups/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

YahooGroups/YahooGroups/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

YahooGroups/YahooGroups/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Yahoo Groups";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <h1 class="text-center">The New <strong style="color:#799DB0">Yahoo Groups</strong> Platform</h1>
        <p class="lead text-center">Your digital community, all in one big place.</p>
        <div class="text-center">
            @Html.ActionLink("Explore the groups", "Index", "Group", new { }, new { @class = "btn btn-light", style = "background-color: #EECB29" })
            @if (ViewBag.UserRole == "unreg")
            {
                <p>or...</p>
                @Html.ActionLink("Join us", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "btn btn-dark", style = "background-color: #974A58" })
            }
        </div>
    </div>
</div>

<div class="d-flex flex-column align-items-center">
    <div class="card mb-3" style="max-width:80%">
        <div class="row">
            <div class="col-md-4">
                <img src="~/Assets/Home/Community.svg" class="card-img" alt="Community" style="object-fit:cover; box-shadow: rgba(128, 128, 128, 0.4) 3px 0px" />
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title text-center">Find the right community for you</h4>
                    <p class="card-text">
                        Join the biggest community aggregation platform on the web and find the one
                        that is just for you. Finding the groups that hold the same interests as you has never been easier.
                        <br /><strong style="color:#799DB0">Yahoo Groups</strong> is the perfect platform that hosts community spaces made by
                        passionate people just like you.
                    </p>
                    <div class="text-center">
                        <a class="btn btn-light text-right" style="background-color:#799DB0">Search groups by topics</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3" style="max-width:80%">
        <div class="row">
            <div class="col-md-4">
                <img src="~/Assets/Home/Connection.svg" class="card-img" alt="Connections" style="object-fit:cover; box-shadow: rgba(128, 128, 128, 0.4) 3px 0px" />
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title text-center">Build meaningfull relationships</h4>
                    <p class="card-text">
                        Our team of dedicated moderators make sure that the platform is a safe environment for people of any
                        backgrounds.<br />
                        We make sure that you can build long-lasting and interesting relationships on our platform and we maintain
                        a high standard of accountability regarding what people post in the groups.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3" style="max-width:80%">
        <div class="row">
            <div class="col-md-4">
                <img src="~/Assets/Home/BuildYourOwn.svg" class="card-img" alt="Community" style="object-fit:cover; box-shadow: rgba(128, 128, 128, 0.4) 3px 0px" />
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title text-center">Build a digital space for your local community</h4>
                    <p class="card-text">
                        Do you want to see your local book club on <strong style="color:#799DB0">Yahoo Groups</strong>?<br />
                    </p>
                    @if (ViewBag.UserRole == "unreg")
                    {
                        <p>Join us now and bring your community online where you can share, discuss and save the special moments right as they are happening.</p>
                        <div class="text-center">
                            @Html.ActionLink("Register now", "Register", "Account", routeValues: null, htmlAttributes: new { @class = "btn btn-light", style = "background-color: #799DB0" })
                        </div>
                    }
                    else
                    {
                        <p>Start by creating a group and inviting all your friends over!</p>
                        <div class="text-center">
                            @Html.ActionLink("Make new group", "CreateGroup", "Group", routeValues: null, htmlAttributes: new { @class = "btn btn-light", style = "background-color: #799DB0" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>